### PR TITLE
app.js: Sort projects acc. to status in scope

### LINKED ISSUE #711: Different order of projects in detailed view
Steps to reproduce:

- Go to https://projects.coala.io/#/projects
- Open the first project
- Click next (arrow)

The next project is not the same as the 2nd project in the grid view.

### PR DESCRIPTION
**Pull request by KVGarg**
The commit sorts the projectsList itself in the JavaScript file
using `orderBy` filter and set the sorted array globally, which
omits the use of `orderBy` filter in `projects.html` file

Fixes #711

### CODE REVIEW

File: resources/js/app.js [hunk 1]
```diff
@@ -105,6 +105,10 @@
                     return mapping[project.status];
                 }
 
+                $scope.sortProjects = function(){
```
Comment (jayvdb) [inline resources/js/app.js]: `(){` -> `() {` ?

It seems we have a mix of styles for this, so not necessary to fix it, or change it.

Need a linting task, including finding a suitable linter to lock down the style choice.

Comment (KVGarg) [reply resources/js/app.js]: > Need a linting task, including finding a suitable linter to lock down the style choice.

[JS Standard](https://github.com/standard/standard) linter used by many of the popular apps. It follows a standard sty;e guide and even it suggests a fix for this issue (`(){ -> () {`)
